# Generated by Django 4.1.5 on 2023-03-21 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("your_Name", models.CharField(max_length=100)),
                ("your_Email", models.EmailField(max_length=254)),
                ("your_Phone", models.CharField(max_length=11)),
                ("your_Company", models.CharField(max_length=100)),
                ("Message", models.CharField(max_length=300)),
            ],
        ),
    ]
